TWITTER_KEY: 'LIk6u2oe0IhyBprKo9IU0A'
TWITTER_SECRET: 'lpyYKR1qyGnuoCCYhclR0BPj0f0e8kpF6oUbai45IcU'

OAUTH_TOKEN: '635215206-tz9koAfadlIF6cfjv8ViSI8tz1ASoKADr3I3wokp'
OAUTH_TOKEN_SECRET: 'hLIK6LEfo8HenfwkKBwU7UD3nLI6EkynTpNS8Moz1rlnj'